[project]
name = "aura"
version = "0.0.1"
description = "A modular, stealthy Python scraper for AnimeHeaven.me built with Playwright and managed with UV. Designed to extract direct download links for anime episodes without triggering bot detection or wasting bandwidth on video streaming."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flet>=0.80.1",
    "playwright>=1.57.0",
]
